// <auto-generated />
using System;
using FastApp.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902210000_AddPackagedAppId")]
    partial class AddPackagedAppId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("FastApp.Services.AppDbContext+AppCategoryMapping", b =>
                {
                    b.Property<string>("AppName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppName");

                    b.ToTable("AppCategories");
                });

            modelBuilder.Entity("FastApp.Services.AppDbContext+HiddenApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HiddenApps");
                });

            modelBuilder.Entity("FastApp.ViewModels.AppItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BonusMinutesDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyLimitMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HotkeyDisplayText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HotkeySequence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HotkeyTriggerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LaunchArguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LaunchDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaunchOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LimitNotifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LimitWarnedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackagedAppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SuppressHotkeyPassthrough")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StrictFocusMode")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeRunning")
                        .HasColumnType("TEXT");

                    b.Property<int>("TodayBonusMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ManagedApps");
                });

            modelBuilder.Entity("FastApp.ViewModels.DailyUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("AfkTimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AfkTimeSpentTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeFocused")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TimeFocusedTicks")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TimeSpentTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppName", "Date");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("FastApp.ViewModels.MacroEventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("MacroEventLogs");
                });

            modelBuilder.Entity("FastApp.ViewModels.SessionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("AppName", "StartTime");

                    b.ToTable("SessionLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
